server:
  port: 8604

spring:
  application:
    name: dd-sms
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/diandi_bbs?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: dev
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        #指定分组
        group: dev
        #指定命名空间
        namespace: dev
  #  rabbitmq:
  #    host: localhost
  #    username: guest
  #    password: guest
  #    port: 5672
  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672      # 注意5672才是RabbitMQ通信端口号！！ 15672是图形化界面的端口
    username: guest
    password: guest
  redis:
    host: localhost #地址
    port: 6379 #端口
    password:
    timeout: 30000 # 连接超时时间（毫秒）
    database: 3 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000